permissions:
  - 'create smart_article content'
  - 'create smart_media_image media'
  - 'delete any smart_article content'
  - 'delete any smart_media_image media'
  - 'delete own smart_article content'
  - 'delete own smart_media_image media'
  - 'delete smart_article revisions'
  - 'edit any smart_media_image media'
  - 'edit any smart_article content'
  - 'edit own smart_media_image media'
  - 'edit own smart_article content'
  - 'revert smart_article revisions'
  - 'view smart_article revisions'
