core.entity_form_display.block_content.cards.default:
  expected_config:
    content:
      view_mode_selection:
        type: options_select
  update_actions:
    change:
      content:
        view_mode_selection:
          type: fvm_options_select
          region: content
          weight: 26
          settings:
            default_option: 'Cards Grid (1xn)'
          third_party_settings: {  }
