core.entity_form_display.paragraph.gallery.default:
  expected_config:
    content:
      view_mode_selection:
        type: options_select
  update_actions:
    change:
      content:
        view_mode_selection:
          type: fvm_options_select
          region: content
          weight: 4
          settings:
            default_option: Default
          third_party_settings: {  }
