permissions:
  - 'create page content'
  - 'delete any page content'
  - 'delete own page content'
  - 'delete page revisions'
  - 'edit any page content'
  - 'edit own page content'
  - 'revert page revisions'
  - 'view page revisions'
